### ISSUE TITLE
Why is _tk now an updatable parent theme?

### ISSUE THREAD

**Issue by DennisWebConsulting** [Themekraft/_tk#47]
Correct me if I'm wrong, but one of the main points of underscores is that it is "a theme meant for hacking so don't use me as a Parent Theme."

_tk turning into a Parent Theme greatly changes the entire concept of what _tk was for orginanlly, at least as I thought. I thought this was a starter theme for building our own theme on top of.

Now it says that you want us to build a child and that you will send theme updates...   : (

**Comment by svenl77** [comment]
Hi @DennisWebConsulting,

_tk is build based on _s and it is meant to be a starter theme. _s is very difficult to use as parent theme and we got a lot of feedback that people want to build a new parent theme based on _tk. Its still a starter theme but we do offer parent theme functionality. This is more about coding and less about usage. 

If you want to use it as a parent theme you can do it. We just want to make sure you can build a parent theme based on _tk.  

One other point is that people use _tk to build themes for wordpress.org and we submitted the _tk for review to the review team just for one reason. To make sure your next wordpress.org parent or child theme will not be rejected because of any issue in the _tk.

I hope this answer clarifiers your question. Let me know if you have any thoughts or question left. We are looking for feedback and prove the direction _tk is going.

**Comment by DennisWebConsulting** [comment]
Thank you. That clarifies what you are doing.
ᐧ
